server:
  port: 8001
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_test
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: userservice
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka
#      ,http://localhost:9999/eureka

xxb: xingxianbao111111111@@@@@@@@
